### ISSUE TITLE
Read API Key from ENV variable

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye_sbt_plugin#10]
Would be great if this plugin would be able to read the API key from an global ENV variable.

**Comment by mp911de** [comment]
This would work like this:

```
set VERSIONEYE_API_KEY=...
```

the env-variable has the highest precedence. An idea would be also `-Dversioneye.api.key=...`, if both are set -> exception

**Comment by reiz** [comment]
+1

**Comment by sslavic** [comment]
Fixed in 0.2.0.
