### ISSUE TITLE
Latest version of all scala libraries is unknown

### ISSUE THREAD

**Issue by sslavic** [versioneye/versioneye_sbt_plugin#5]
Create a sbt project, add any scala library as dependency (e.g "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"), publish project to versioneye using versioneye sbt plugin - "Newest" column for dependency will be "UNKNOWN".

It seems scala binary version suffix, present in artifact id of all scala libraries (e.g. "_2.11" in http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/ ), is not used when resolving latest version of a library.

**Comment by reiz** [comment]
@mp911de Can you please take a look to this?

**Comment by mp911de** [comment]
Yep.

**Comment by reiz** [comment]
@sslavic Can this be closed now? /cc @mp911de

**Comment by sslavic** [comment]
Yep, fixed in 0.1.1
