### ISSUE TITLE
createProject writes versioneye.properties with hardcoded heading

### ISSUE THREAD

**Issue by sslavic** [versioneye/versioneye_sbt_plugin#8]
On createProject "Properties for https://www.VersionEye.com" heading is always written in versioneye.properties file regardless of VersionEye server URL
(see https://github.com/versioneye/versioneye_sbt_plugin/blob/master/src/main/scala/com/versioneye/PropertiesUtil.scala#L32 )

This is fine for public VersionEye server, but not for enterprise VersionEye deployments.

Please consider using configured baseUrl instead.

**Comment by reiz** [comment]
I see. That should be easy for @mp911de :)

**Comment by reiz** [comment]
@sslavic This should be fixed with this pull request: https://github.com/versioneye/versioneye_sbt_plugin/pull/12. I will publish a new release to Maven Central today!

**Comment by sslavic** [comment]
Fixed with 0.2.0.

Exactly same issue exists in versioneye maven plugin.

**Comment by reiz** [comment]
Will fix that in the next version of the VersionEye Maven Plugin.
